2023-06-22 20:12:27,937 [INFO] Started flask app: app
2023-06-22 20:14:00,925 [INFO] Started flask app: app
2023-06-22 20:14:04,845 [INFO] Started flask app: app
2023-06-22 20:14:04,856 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-06-22 20:14:04,856 [INFO] [33mPress CTRL+C to quit[0m
2023-06-22 20:14:50,858 [INFO] 127.0.0.1 - - [22/Jun/2023 20:14:50] "GET / HTTP/1.1" 200 -
2023-06-22 20:15:09,890 [INFO] 127.0.0.1 - - [22/Jun/2023 20:15:09] "GET / HTTP/1.1" 200 -
2023-06-22 20:15:26,433 [INFO] 127.0.0.1 - - [22/Jun/2023 20:15:26] "[31m[1mPOST / HTTP/1.1[0m" 405 -
2023-06-22 20:15:32,030 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:15:32,034 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:15:32,040 [INFO] 127.0.0.1 - - [22/Jun/2023 20:15:32] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:32,076 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:32,077 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:20:32,083 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:32] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:32,899 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:32,900 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:20:32,905 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:32] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:33,459 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:33,461 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:20:33,469 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:33] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:37,084 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:37,085 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:20:37,090 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:37] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:37,961 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:37,963 [ERROR] Exception on /assert [POST]
Traceback (most recent call last):
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\vollaiballkb\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "D:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:20:37,969 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:37] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:49,611 [INFO] Started flask app: app
2023-06-22 20:20:49,625 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-06-22 20:20:49,625 [INFO] [33mPress CTRL+C to quit[0m
2023-06-22 20:20:52,226 [INFO] Asserting fact: gay(ciccio)
2023-06-22 20:20:52,228 [INFO] 127.0.0.1 - - [22/Jun/2023 20:20:52] "[35m[1mPOST /assert HTTP/1.1[0m" 500 -
2023-06-22 20:20:52,343 [ERROR] Error on request:
Traceback (most recent call last):
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\vollAIballKB\src\app.py", line 43, in assertz
    knowledgeBase.assertz(fact)
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "d:\Archivio\Anaconda3\envs\vollAIballKB\Lib\site-packages\pyswip\prolog.py", line 91, in __call__
    swipl_fid = PL_open_foreign_frame()
                ^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000050
2023-06-22 20:35:59,882 [INFO] Started flask app: app
2023-06-22 20:35:59,902 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-06-22 20:35:59,902 [INFO] [33mPress CTRL+C to quit[0m
2023-06-22 20:37:02,844 [INFO] Started flask app: app
2023-06-22 20:37:02,857 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-06-22 20:37:02,858 [INFO] [33mPress CTRL+C to quit[0m
